CREATE TABLE dbo.Inventory
(
  Id INT NOT NULL PRIMARY KEY IDENTITY,
  ProductId INT NOT NULL,
  Quantity INT NOT NULL DEFAULT 1,
  Price MONEY NOT NULL,
  PurchaseAt DATETIME2 NOT NULL DEFAULT getutcdate(),
  CreatedAt DATETIME2 NOT NULL DEFAULT getutcdate()
)