CREATE TABLE dbo.Sale
(
  Id INT NOT NULL PRIMARY KEY IDENTITY,
  UserId INT NOT NULL DEFAULT 0,
  SaleDate DATETIME2 NOT NULL DEFAULT getutcdate(),
  SubTotal MONEY NOT NULL DEFAULT 0,
  Tax MONEY NOT NULL DEFAULT 0,
  Total MONEY NOT NULL DEFAULT 0,
  CreatedAt DATETIME2 NOT NULL DEFAULT getutcdate()
  --CONSTRAINT fk_Sale_ref_User FOREIGN KEY (UserId) REFERENCES dbo.User(Id)
)